# -*- coding: utf-8 -*-
"""Frames_to_csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WveQ8kfK3-iuwqcYNY3fdvUwFWvyf_rs
"""

#Mount the drive
from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd
import os

"""As of now, we have split our data into train & test and have extracted (WRITE NUM) frames per video, stored them in a folder correspondig to that video.

Eg: crime_data--->Train--->Abuse--->Video1--->Frames of Video1

Similarly

crime_data--->Test--->Abuse--->Video1--->Frames of Video1
"""

#Directory containing all the data.
root_data_dir='/content/gdrive/MyDrive/crime_data'

#Training and Testing data directory
train_data_path = os.path.join(root_data_dir,'Train')
test_data_path = os.path.join(root_data_dir,'Test')

#Create directories to store csv for Train and Test Video.

if not os.path.exists(os.path.join(root_data_dir,'Train_csv')):
    os.mkdir(os.path.join(root_data_dir,'Train_csv'))
if not os.path.exists(os.path.join(root_data_dir,'Test_csv')):
    os.mkdir(os.path.join(root_data_dir,'Test_csv'))

#These are the destination paths to store your csvs(one for each vide)

train_csv_directory=os.path.join(root_data_dir,'Train_csv')
test_csv_directory=os.path.join(root_data_dir,'Test_csv')

def generate_csv(data_path,csv_directory):
    
    #List of categories ['Abuse','Arson'...etc]
    data_dir_list = os.listdir(data_path)
    
    print("Classes: ",data_dir_list)
    
    #Let's loop over every category
    for data_dir in data_dir_list:
         
        label = str(data_dir)  #eg label='Abuse'
        
        #List of folders corresponding to videos under this class :: containing frames
        video_list = os.listdir(os.path.join(data_path,data_dir))
        
        #Let's loop over every video-folder
        for vid in video_list:
        
            train_df = pd.DataFrame(columns=['FileName', 'Label', 'ClassName'])
            
            #List of all the frames in this video.
            img_list = os.listdir(os.path.join(data_path,data_dir,vid))

            #Let's loop over every frame in the video
            for img in img_list:
                
                #This is the path of the image in your system
                img_path = os.path.join(data_path,data_dir,vid,img)

                #Append the path
                train_df = train_df.append({'FileName': img_path, 'Label': label,'ClassName':data_dir },ignore_index=True)

            #File name :: Abuse/Video1
            file_name='{}_{}.csv'.format(data_dir,vid)

            #Save in the destination
            train_df.to_csv('{}/{}'.format(csv_directory , file_name))

generate_csv(train_data_path,train_csv_directory)

generate_csv(test_data_path,test_csv_directory)